name: Docker validation build for the latest config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Seafile CLI image
      run: docker build . --file latest.dockefile --tag seafile-cli:latest
